### ISSUE TITLE
Add a noscript fallback message

### ISSUE THREAD

**Issue by jeremyredhead** [TiddlyWiki/tiddlywiki.org-gh-pages#1]
Hi, I'm not sure if this is the right repo to be raising this issue in,
but I think the HelloThere tiddler should be included in the static html with some message about JS,
just like/similarly to [TiddlyWiki.com](https://TiddlyWiki.com)

I'd be glad to put together the PR for this if someone can just point me to the right repo to use
(I'm assuming it's not this one)

**Comment by Jermolene** [comment]
Hi @jeremyredhead the source for TiddlyWiki links is at https://github.com/TiddlyWiki/TiddlyWikiLinks, I'd welcome a PR if you'd be interested.

**Comment by Jermolene** [comment]
Thinking about it, TiddlyWiki Links should probably have a splash screen too.

**Comment by jeremyredhead** [comment]
Err, I was rather looking for the source for TiddlyWiki.org, *not* Links.TiddlyWiki.org -- there doesn't appear to be a branch or folder for the "main" tiddlywiki.org site in the repo you linked

**Comment by Jermolene** [comment]
Apologies @jeremyredhead!

The tiddlywiki.org content is part of the main TiddlyWiki 5 repo:

https://github.com/Jermolene/TiddlyWiki5/tree/tiddlywiki-com/editions/tw.org

Content update PRs should be sent to the tiddlywiki-com branch; the CI system will automatically rebuild this repo when the PR is merged.

**Comment by jeremyredhead** [comment]
fixed by https://github.com/Jermolene/TiddlyWiki5/commit/7459ccfed515b5040cf3072de6267abcca3b7fa5
